# ===========================================
# IMAGE VALUES (Used by Jenkins + Helm)
# ===========================================

frontend:
  image:
    repository: "prashantkpowar/frontend"
    tag: "latest"

  tolerations:
    - key: "tier"
      operator: "Equal"
      value: "frontend"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "role"
                operator: "In"
                values:
                  - frontend


backend:
  image:
    repository: "prashantkpowar/backend"
    tag: "latest"

  tolerations:
    - key: "tier"
      operator: "Equal"
      value: "backend"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "role"
                operator: "In"
                values:
                  - backend


# ===========================================
# DATABASE VALUES (Jenkins automatically sets db.host)
# ===========================================

db:
  host: ""         # Provided by Terraform output
  password: ""     # Only if your backend uses DB password


# ===========================================
# SERVICE CONFIG (Optional)
# ===========================================

service:
  frontendPort: 80
  backendPort: 8080