# ===========================================
# IMAGE VALUES (Used by Jenkins + Helm)
# ===========================================

frontend:
  image:
    repository: "prashantkpowar/frontend"
    tag: "latest"

  tolerations:
    - key: "tier"
      operator: "Equal"
      value: "frontend"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "role"
                operator: "In"
                values:
                  - frontend


backend:
  image:
    repository: "prashantkpowar/backend"
    tag: "latest"

  tolerations:
    - key: "tier"
      operator: "Equal"
      value: "backend"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "role"
                operator: "In"
                values:
                  - backend


# ===========================================
# DATABASE VALUES
# ===========================================

db:
  host: ""           # Jenkins / Terraform will inject Aurora endpoint
  port: "3306"
  user: "dbadmin"
  name: "appdb"
  password: ""       # Jenkins credential or secret


# ===========================================
# SERVICE CONFIG
# ===========================================

service:
  frontendPort: 80
  backendPort: 8080