apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - backend

      tolerations:
        - key: "tier"
          operator: "Equal"
          value: "backend"
          effect: "NoSchedule"

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          env:
            - name: DB_HOST
              value: "{{ .Values.db.host }}"

            - name: DB_PASSWORD
              value: "{{ .Values.db.password }}"

          ports:
            - containerPort: 8080